version: '2'

services:
  ddserver1:
    image: ddserver:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    depends_on:
      - ddserver2
    links:
      - "ddserver2:next"
    ports:
      - "50051:50051"
    environment:
      - REMOTE_DEBUGGING

  ddserver2:
    image: ddserver:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    depends_on:
      - ddserver3
    links:
      - "ddserver3:next"
    ports:
      - "50052:50052"
    environment:
      - REMOTE_DEBUGGING

  ddserver3:
    image: ddserver:debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    ports:
      - "50053:50053"
    environment:
      - REMOTE_DEBUGGING
